### PR TITLE
Expensivetests- short section on when tests get expensive

### PR DESCRIPTION
**Pull request by rjjgilham**

### CODE REVIEW

**Comment by rainsworth** [comment]
Thank you so much for this contribution @rjjgilham - we are working on getting this reviewed and merged 👍

**Review by rainsworth — APPROVED** [review]
Thanks for the comments on computational expense!

**Comment by rainsworth** [comment]
@alexmorley I attempted to rename a chapter for consistency but seem to have broken the netlify checks. 😑 Renamed it back but still broken, should probably revert commits instead. Help?

**Comment by alexmorley** [comment]
There is a bug at the moment where every build fails the first time but passes as soon as I click 're-run without cache'. Haven't had time to dig into it yet. Gonna open an issue on the main repo so we can keep track of it though.

**Comment by alexmorley** [comment]
(i.e. this was likely nothing to do with you!)

**Comment by rainsworth** [comment]
Oh brilliant, I thought I was going mad! Thanks @alexmorley

**Pull request merged**
