### PR TITLE
[WIP] Chapter on Make for Reproducible Research

### PR DESCRIPTION
**Pull request by GjjvdBurg**
This is a draft of a chapter on using Make for reproducible research. It is based primarily on [an informal talk](https://gertjanvandenburg.com/files/talk/make.html) I gave a few months ago at the Alan Turing Institute. It also describes a real research project that uses Make for reproducibility.

Known to do items:

- [ ] Add a glossary
- [ ] Add more images (e.g. from the result pdf in the tutorial)
- [ ] Move some of the links in the Further Reading to the Bibliography
- [ ] Provide proper syntax highlighting (? - not sure how to do this in JupyterBook)
- [ ] Finalise TOC.

Finally, while I wrote the tutorial from scratch, I later discovered that there are several blog posts online that also describe the use of Make for reproducibility. It might be useful to include these in the bibliography. These links are:

- https://kbroman.wordpress.com/tag/reproducible-research/
- http://zmjones.com/make/
- https://bsmith89.github.io/make-bml/
- https://kbroman.org/minimal_make/
- http://stat545.com/automation04_make-activity.html

### CODE REVIEW

**Comment by alexmorley** [comment]
Looks cool! Feel free to tag me in here once this is ready for review :)

**Comment by rainsworth** [comment]
Thank you @GjjvdBurg!

@alexmorley - would you be able to review the chapter as-is? If it's ok, we can go ahead and merge it and add what's left to be done to an issue.

**Comment by alexmorley** [comment]
I haven't had time to execute all the commands in the tutorial. But I've read through and it all seems clear to me. Definitely good for an initial merge. @GjjvdBurg if possilbe maybe you could then open an issue on the new repo with the list of things you had on your todo (we are going to move all the chapters back to that repo soon)?

**Review by alexmorley — APPROVED** [review]

**Comment by GjjvdBurg** [comment]
Thanks for taking a look @alexmorley! I could certainly open a new issue, but what is the "new" repo?

**Comment by alexmorley** [comment]
The new repo is actually the old repo. We tried to split out the book itself from everything else but it has ended up being a bit confusing so we are moving back. So everything will live here --> https://github.com/alan-turing-institute/the-turing-way

**Comment by alexmorley** [comment]
Sorry for the confusion! And thanks for contributing, I think this chapter will be super useful :rocket:

**Comment by GjjvdBurg** [comment]
Thanks for merging @alexmorley! I've created an issue for the remaining things.

**Comment by rainsworth** [comment]
Thank you @GjjvdBurg & @alexmorley! 🎉

**Pull request merged**
