### PR TITLE
New chapter on Risk Assessment

### PR DESCRIPTION
**Pull request by rjjgilham**

### CODE REVIEW

**Comment by rjjgilham** [comment]
Note related PR for the figure...

**Review by Biostew — APPROVED** [review]
Reviewed - No changes to be made.

**Review by pherterich — APPROVED** [review]
Looks great - thank you! Did you create the figure? Would be great to clarify in case anyone wants to re-use it :smile:

**Comment by rjjgilham** [comment]
Hello,
Yes I created it from scratch so good to reuse!

**Pull request merged**
